name       : libinsane
version    : 1.0.1
release    : 1
source     :
    - https://gitlab.gnome.org/World/OpenPaperwork/libinsane/-/archive/1.0.1/libinsane-1.0.1.tar.bz2 : fe577db5b07946fae90f4ecd00e17a963c63f6a9b8ad58f33b971f2cc3e5e0e9
license    : LGPL-3.0-or-later
component  : programming.library
summary    : Library to access scanners
description: |
    Library to access scanners
builddeps  :
    - pkgconfig(sane-backends)
    - gtk-doc
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Option to disable not configurable with meson currently.
    rm -fr $installdir/usr/share/gtk-doc/
