name       : libinsane
version    : 1.0.10
release    : 8
source     :
    - https://gitlab.gnome.org/World/OpenPaperwork/libinsane/-/archive/1.0.10/libinsane-1.0.10.tar.gz : a9b8daaef03eb3bc4a8e638131e506ff3c2f99f715170da572e7f5ce7ba76467
homepage   : https://gitlab.gnome.org/World/OpenPaperwork/libinsane
license    : LGPL-3.0-or-later
component  : programming.library
summary    : Library to access scanners
description: |
    Libinsane is the library to access scanners
builddeps  :
    - pkgconfig(sane-backends)
    - gtk-doc
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Option to disable not configurable with meson currently.
    rm -fr $installdir/usr/share/gtk-doc/
