name       : libinsane
version    : 1.0.3
release    : 4
source     :
    - https://gitlab.gnome.org/World/OpenPaperwork/libinsane/-/archive/1.0.3/libinsane-1.0.3.tar.gz : 78282d848845875c0fc25576c1ad2034b816982845440a40a0f618447db4a1e2
license    : LGPL-3.0-or-later
component  : programming.library
summary    : Library to access scanners
description: |
    Library to access scanners
builddeps  :
    - pkgconfig(sane-backends)
    - gtk-doc
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
    # Option to disable not configurable with meson currently.
    rm -fr $installdir/usr/share/gtk-doc/
